### ISSUE TITLE
Embeds sentences programmatically

### ISSUE THREAD

**Issue by NooneBug** [allenai/kb#6]
Hi,

I want to produce the contextual embeddings of sentences programmatically with KnowBert but the README talks about how to reproduce results and how to fine tune on downstream tasks.

How can I use this repository to obtain only contextual embeddings?

**Comment by acarrera94** [comment]
I would like to know this as well. Thanks!

**Comment by matt-peters** [comment]
Added some documentation in #10 that includes minimal code to load a trained model and embed raw text programmatically.

**Comment by NooneBug** [comment]
Thank a lot :)
